# Generated by Django 5.1.3 on 2024-11-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sait', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='solution',
        ),
    ]
